version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypass
  
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:8080

  backend:
    build: 
      context: .

