- name: Copy file and Delete
  hosts: ans.efr

  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /etc/fstab
        dest: /tmp/fstab-copy-from-it1
        owner: ast
        group: ast
        mode: '0644'

    - name: Delete copied file
      ansible.builtin.file:
        path: /tmp/fstab-copy-from-it1
        state: absent
