- name: Install docker and add user to docker-group
  hosts: ans.efr

  tasks:
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
        filename: docker

    - name: Install Docker 23.0.1-1
      ansible.builtin.apt:
        name:
          - docker-ce=5:23.0.1-1~ubuntu.22.04~jammy
          - docker-ce-cli=5:23.0.1-1~ubuntu.22.04~jammy
          - containerd.io
        state: present
        update_cache: true

    - name: Add user dmitry to docker-group
      ansible.builtin.user:
        name: dmitry
        groups: docker
        append: true
